import { File } from '../types';

declare const JSZip: any;

export const zipService = {
  downloadProject: async (files: File[], projectName: string) => {
    if (typeof JSZip === 'undefined') {
      console.error('JSZip not loaded');
      return;
    }

    const zip = new JSZip();
    const folder = zip.folder(projectName.replace(/\s+/g, '-').toLowerCase());

    files.forEach(file => {
      folder.file(file.name, file.content);
    });

    // Add a basic README if not present
    if (!files.find(f => f.name === 'README.md')) {
      folder.file('README.md', `# ${projectName}\n\nGenerated by Agentic AI App Builder.`);
    }

    const content = await zip.generateAsync({ type: 'blob' });
    
    // Create download link
    const url = window.URL.createObjectURL(content);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${projectName.replace(/\s+/g, '-').toLowerCase()}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  }
};